config/routes.rb
Rails.application.routes.draw do
  resources :dados
  root :to => redirect('/trechos')
  resources :trechos
  resources :cidades

  get '/cadastrar_cidades' => 'cidades#index'
  get '/dados' => 'dados#index'
  
  get '/search' => 'trechos#search', :as => :search_trechos

end

app/models/cidade.rb
class Cidade < ActiveRecord::Base
end

app/models/dado.rb
class Dado < ActiveRecord::Base
end

app/models/trecho.rb
class Trecho < ActiveRecord::Base
    scope :origem, -> (origem) { where origem: origem }
    scope :destino, -> (destino) { where destino: destino }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cidades_controller.rb
class CidadesController < ApplicationController
  before_action :set_cidade, only: [:show, :edit, :update, :destroy]

  # GET /cidades
  # GET /cidades.json
  def index
    @cidades = Cidade.all
  end

  # GET /cidades/1
  # GET /cidades/1.json
  def show
  end

  # GET /cidades/new
  def new
    @cidade = Cidade.new
  end

  # GET /cidades/1/edit
  def edit
  end

  # POST /cidades
  # POST /cidades.json
  def create
    @cidade = Cidade.new(cidade_params)

    respond_to do |format|
      if @cidade.save
        format.html { redirect_to @cidade, notice: 'Cidade was successfully created.' }
        format.json { render :show, status: :created, location: @cidade }
      else
        format.html { render :new }
        format.json { render json: @cidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cidades/1
  # PATCH/PUT /cidades/1.json
  def update
    respond_to do |format|
      if @cidade.update(cidade_params)
        format.html { redirect_to @cidade, notice: 'Cidade was successfully updated.' }
        format.json { render :show, status: :ok, location: @cidade }
      else
        format.html { render :edit }
        format.json { render json: @cidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cidades/1
  # DELETE /cidades/1.json
  def destroy
    @cidade.destroy
    respond_to do |format|
      format.html { redirect_to cidades_url, notice: 'Cidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cidade
      @cidade = Cidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cidade_params
      params.require(:cidade).permit(:nome, :estado)
    end
end

app/controllers/dados_controller.rb
class DadosController < ApplicationController
  before_action :set_dado, only: [:show, :edit, :update, :destroy]

  # GET /dados
  # GET /dados.json
  def index
    @dados = Dado.all
  end

  # GET /dados/1
  # GET /dados/1.json
  def show
  end

  # GET /dados/new
  def new
    @dado = Dado.new
  end

  # GET /dados/1/edit
  def edit
  end

  # POST /dados
  # POST /dados.json
  def create
    @dado = Dado.new(dado_params)

    respond_to do |format|
      if @dado.save
        format.html { redirect_to @dado, notice: 'Dado was successfully created.' }
        format.json { render :show, status: :created, location: @dado }
      else
        format.html { render :new }
        format.json { render json: @dado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dados/1
  # PATCH/PUT /dados/1.json
  def update
    respond_to do |format|
      if @dado.update(dado_params)
        format.html { redirect_to @dado, notice: 'Dado was successfully updated.' }
        format.json { render :show, status: :ok, location: @dado }
      else
        format.html { render :edit }
        format.json { render json: @dado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dados/1
  # DELETE /dados/1.json
  def destroy
    @dado.destroy
    respond_to do |format|
      format.html { redirect_to dados_url, notice: 'Dado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dado
      @dado = Dado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dado_params
      params.require(:dado).permit(:nome, :sobrenome, :cpf, :sexo, :email, :pagamento)
    end
end

app/controllers/trechos_controller.rb
class TrechosController < ApplicationController
  before_action :set_trecho, only: [:show, :edit, :update, :destroy]

  # GET /trechos
  # GET /trechos.json
  def index
    @trechos = Trecho.all   
  end

  def search
    @trechos = Trecho.where(nil) # creates an anonymous scope
    if params[:search].present?
      @trechos = @trechos.origem(params[:search][:origem]) if params[:search][:origem].present?   
      @trechos = @trechos.destino(params[:search][:destino]) if params[:search][:destino].present? 
    end
  end

  # GET /trechos/1
  # GET /trechos/1.json
  def show
  end

  # GET /trechos/new
  def new
    @trecho = Trecho.new
  end

  # GET /trechos/1/edit
  def edit
  end

  # POST /trechos
  # POST /trechos.json
  def create
    @trecho = Trecho.new(trecho_params)

    respond_to do |format|
      if @trecho.save
        format.html { redirect_to @trecho, notice: 'Trecho was successfully created.' }
        format.json { render :show, status: :created, location: @trecho }
      else
        format.html { render :new }
        format.json { render json: @trecho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trechos/1
  # PATCH/PUT /trechos/1.json
  def update
    respond_to do |format|
      if @trecho.update(trecho_params)
        format.html { redirect_to @trecho, notice: 'Trecho was successfully updated.' }
        format.json { render :show, status: :ok, location: @trecho }
      else
        format.html { render :edit }
        format.json { render json: @trecho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trechos/1
  # DELETE /trechos/1.json
  def destroy
    @trecho.destroy
    respond_to do |format|
      format.html { redirect_to trechos_url, notice: 'Trecho was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trecho
      @trecho = Trecho.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trecho_params
      params.require(:trecho).permit(:origem, :destino, :data_ida, :horario_ida, :data_volta, :horario_volta)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/dados_helper.rb
module DadosHelper
end

app/helpers/trechos_helper.rb
module TrechosHelper
end

app/views/cidades/_form.html.erb
<%= form_for(@cidade) do |f| %>
  <% if @cidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cidade.errors.count, "error") %> prohibited this cidade from being saved:</h2>

      <ul>
      <% @cidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" id="Alin">
    <p  id="TextTam" >Nome: <%= f.text_field :nome %></p>
  </div>

  <div class="field" id="Alin">
    <p  id="TextTam" >Estado: <%= f.text_field :estado %></p>
  </div>
  
  <div class="actions" id="Alin">
    <%= f.submit %>
  </div>
<% end %>

app/views/cidades/edit.html.erb
<h1>Editing Cidade</h1>

<%= render 'form' %>

<%= link_to 'Show', @cidade %> |
<%= link_to 'Back', cidades_path %>

app/views/cidades/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <tr>
  <td height="50px" colspan="5" id="idColorUm" ></td>
  </tr>
  <tr>
    <td colspan="3" ><h1>LISTA DE CIDADES</h1></td>
  </tr>
  <tr>
    <td wigth="10%" height="150px"><a id="menu-button" id="menu-button-green" href="/trechos"> Trechos </a></td>
    <td ><a id="menu-button" id="menu-button-green" href="/dados"> Dados </a></td>
  </tr>
    <tr>
      <td width="30%"id="idTextDois">Nome</td>
      <td   id="idText">Estado</td>
      
    </tr>

    <% @cidades.each do |cidade| %>
      <tr>
        <td id="idTextAlinDois"><%= cidade.nome %></td>
        <td id="idTextAlin"><%= cidade.estado %></td>
        <td id="idTextAlin"><%= link_to 'Mostrar', cidade %></td>
    <!--    <td id="idTextAlin"><%= link_to 'Edit', edit_cidade_path(cidade) %></td> -->
    <!--   <td id="idTextAlin"><%= link_to 'Destroy', cidade, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
    <tr>
      <td colspan="3" height="200px" id="idTextTres"><%= link_to 'Nova Cidade', new_cidade_path %>
      </td>
    </tr>
</table>

<br>

app/views/cidades/new.html.erb
<table>
    <tr>
    <td height="50px" colspan="2" id="idColorUm"></td>
    </tr>
    <tr>
        <td height="40px" colspan="2" ><h2 id="Alin">NOVA CIDADE</h2></td>
    </tr>
</table>

<%= render 'form' %>

<%= link_to 'Back', cidades_path %>

app/views/cidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cidade.nome %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @cidade.estado %>
</p>

<%= link_to 'Edit', edit_cidade_path(@cidade) %> |
<%= link_to 'Back', cidades_path %>

app/views/dados/_form.html.erb
<%= form_for(@dado) do |f| %>
  <% if @dado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dado.errors.count, "error") %> prohibited this dado from being saved:</h2>

      <ul>
      <% @dado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" id="Alin">
  <p  id="TextTam" >Nome: <%= f.text_field :nome %></p>
  </div>

  <div class="field" id="Alin">
  <p  id="TextTam" >Sobrenome: <%= f.text_field :sobrenome %></p>
  </div>

  <div class="field" id="Alin">
  <p  id="TextTam" >CPF: <%= f.text_field :cpf %></p>
  </div>

  <div class="field" id="Alin">
  <p  id="TextTam" >Sexo: <%= f.text_field :sexo %></p>
  </div>

  <div class="field" id="Alin">
  <p  id="TextTam" >E-mail: <%= f.text_field :email %></p>
  </div>

  <div class="field" id="Alin">
  <p  id="TextTam" >Pagamento: <%= f.text_field :pagamento %></p>
  </div>

  <div class="actions" id="Alin">
    <%= f.submit %>
  </div>
<% end %>

app/views/dados/edit.html.erb
<h1>Editing Dado</h1>

<%= render 'form' %>

<%= link_to 'Show', @dado %> |
<%= link_to 'Back', dados_path %>

app/views/dados/index.html.erb
<p id="notice"><%= notice %></p>

<table>
    <tr>
    <td colspan="9" height="50px" width="100%" id="idColorUm"></td>
    </td>
    <tr>
      <td colspan="9" height="40px"><h1>LISTA DE DADOS</h1></td>
    </td>
    <tr>
      <td width="4%" height="150px"><a id="menu-button" id="menu-button-green" href="/trechos"> Dados </a></td>
      <td colspan="8"><a id="menu-button" id="menu-button-green" href="/cadastrar_cidades"> Cidades </a></td>
    </td>
    <tr>
      <td id="idTextDois">Nome</td>
      <td id="idText">Sobrenome</td>
      <td id="idText">Cpf</td>
      <td id="idText">Sexo</td>
      <td id="idText">Email</td>
      <td id="idText">Pagamento</td>
    </tr>

    <% @dados.each do |dado| %>
      <tr>
        <td id="idTextAlinDois"><%= dado.nome %></td>
        <td id="idTextAlin"><%= dado.sobrenome %></td>
        <td id="idTextAlin"><%= dado.cpf %></td>
        <td id="idTextAlin"><%= dado.sexo %></td>
        <td id="idTextAlin"><%= dado.email %></td>
        <td id="idTextAlin"><%= dado.pagamento %></td>
        <td colspan="3" id="idTextTres"><%= link_to 'Mostrar', dado %></td>
<!--        <td><%= link_to 'Edit', edit_dado_path(dado) %></td> -->
<!--        <td><%= link_to 'Destroy', dado, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
    <tr>
      <td colspan="7" height="200px" id="idTextTres"><%= link_to 'Novo Dado', new_dado_path %></td>
    </tr>
</table>

app/views/dados/new.html.erb
<table>
    <tr>
    <td height="50px" colspan="2" id="idColorUm"></td>
    </tr>
    <tr>
        <td height="40px" colspan="2" ><h2 id="Alin">NOVO DADO</h2></td>
    </tr>
</table>

<%= render 'form' %>

<%= link_to 'Back', dados_path %>

app/views/dados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @dado.nome %>
</p>

<p>
  <strong>Sobrenome:</strong>
  <%= @dado.sobrenome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @dado.cpf %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @dado.sexo %>
</p>

<p>
  <strong>Email:</strong>
  <%= @dado.email %>
</p>

<p>
  <strong>Pagamento:</strong>
  <%= @dado.pagamento %>
</p>

<%= link_to 'Edit', edit_dado_path(@dado) %> |
<%= link_to 'Back', dados_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travels</title>
  <link rel="stylesheet" href="https://railsgirls.com/assets/bootstrap.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

<footer>
  <div class="container" id="TextLay">
    Promoções de passagens saindo de:
  </div>
</footer>

</body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container" id="Alin">
      <br>
      <a class="brand" href="/"> &nbsp; &nbsp; Parintins &nbsp; &nbsp;</a>
      <a class="brand" href="/"> &nbsp; &nbsp; Maués &nbsp; &nbsp;</a>
      <a class="brand" href="/"> &nbsp; &nbsp; Manaus &nbsp; &nbsp;</a>
      <ul class="nav">
      </ul>
    </div>
  </div>
</div>

</html>

app/views/trechos/_form.html.erb
<%= form_for(@trecho) do |f| %>
  <% if @trecho.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trecho.errors.count, "error") %> prohibited this trecho from being saved:</h2>

      <ul>
      <% @trecho.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
    <td height="90px" id="idTextAlin"><p id="TextTam"><b>PASSAGENS DE IDA E VOLTA</b></p></td>
    </tr>
</table>

  <div class="field" id="Alin">
    <p  id="TextTam" >Origem: <%= f.text_field :origem %></p>
  </div>

  <div class="field" id="Alin">
    <p  id="TextTam" >Destino: <%= f.text_field :destino %></p>
  </div>

  <div class="field" id="Alin">
    <p  id="TextTam" >Data Ida: <%= f.date_select :data_ida %></p>
  </div>

  <div class="field" id="Alin">
   <p  id="TextTam" >Horário Ida: <%= f.text_field :horario_ida %></p>
  </div>

  <div class="field" id="Alin">
    <p  id="TextTam" >Data Volta: <%= f.date_select :data_volta %></p> 
  </div>

  <div class="field" id="Alin">
    <p  id="TextTam" >Horário Volta: <%= f.text_field :horario_volta %></p>
  </div>

  <div class="actions" id="Alin"> 
    <%= f.submit %>
  </div>
<% end %>

app/views/trechos/edit.html.erb
<h1>Editing Trecho</h1>

<%= render 'form' %>

<%= link_to 'Show', @trecho %> |
<%= link_to 'Back', trechos_path %>

app/views/trechos/index.html.erb
<html>

  <p id="notice"><%= notice %></p>

  <body>
    <table>
        <tr>
          <td id="idColorUm" height="240px" colspan="7">
          </td>
        </tr>
        <tr>
          <td height="50px" width="100px"><a id="menu-button" id="menu-button-green" href="/search"> Pesquisa </a></td>
          <td width="90px"><a id="menu-button" id="menu-button-green" href="/cadastrar_cidades"> Cidades </a></td>
          <td colspan="5" width="100px"><a id="menu-button" id="menu-button-green" href="/dados"> Dados </a></td>
        </tr>  
        <tr>
          <td height="100px" colspan="7"><h1>LISTA DE TRECHOS</h1></td>
        </tr>
         
        <tr>
          <td id="idTextDois">Origem</td>
          <td id="idText">Destino</td>
          <td id="idText">Data Ida</td>
          <td id="idText">Horario Ida</td>
          <td id="idText">Data Volta</td>
          <td id="idText">Horario Volta</td>
          <td></td>          
        </tr>

        <% @trechos.each do |trecho| %>
          <tr>
            <td id="idTextAlinDois"><%= trecho.origem %></td>
            <td id="idTextAlin"><%= trecho.destino %></td>
            <td id="idTextAlin"><%= trecho.data_ida %></td>
            <td id="idTextAlin"><%= trecho.horario_ida %></td>
            <td id="idTextAlin"><%= trecho.data_volta %></td>
            <td id="idTextAlin"><%= trecho.horario_volta %></td>
            <td id="idTextTres"><%= link_to 'Mostrar', trecho %></td>
          </tr>
        <% end %>
        <tr>
          <td colspan="7" height="200px" id="idTextTres"><%= link_to 'Novo Trecho', new_trecho_path %></td>
        </tr>
    </table>
  </body>
</html>

app/views/trechos/new.html.erb
<table>
    <tr>
    <td height="50px" colspan="2" id="idColorUm"></td>
    </tr>
    <tr>
        <td height="40px" colspan="2" ><h2 id="Alin">NOVO TRECHO</h2></td>
    </tr>
</table>


<%= render 'form' %>

<%= link_to 'Back', trechos_path %>

app/views/trechos/search.html.erb
<table>
    <tr>
    <td height="50px" id="idColorUm"></td>
    </tr>
</table>

<%= form_for :search, url: search_trechos_path, method: :get do |form| %>
    <p  id="TextTam" >Buscar Por Origem: <%= form.text_field :origem, value: params[:origem].presence && params[:origem] %>&nbsp; <%= form.submit 'Buscar' %></p>
    <p  id="TextTam" >Buscar Por Destino: <%= form.text_field :destino, value: params[:destino].presence && params[:destino] %>&nbsp; <%= form.submit 'Buscar' %></p>
    
<% end %>
  

<% @trechos.each do |trecho| %>
    <br>
    <table>
        <tr>
            <td colspan="9"></td>
        </tr>
        <tr>
            <td id="idTextAlin"><%= trecho.origem %></td>
            <td id="idTextAlin"><%= trecho.destino %></td>
            <td id="idTextAlin"><%= trecho.data_ida %></td>
            <td id="idTextAlin"><%= trecho.horario_ida %></td>
            <td id="idTextAlin"><%= trecho.data_volta %></td>
            <td id="idTextAlin"><%= trecho.horario_volta %></td>
            <td id="idTextAlin" colspan="3"><%= link_to 'Show', trecho %></td>
<!--            <td><%= link_to 'Edit', edit_trecho_path(trecho) %></td> -->
<!--            <td><%= link_to 'Destroy', trecho, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        </tr>
    </br>
    </table>
<% end %>

app/views/trechos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Origem:</strong>
  <%= @trecho.origem %>
</p>

<p>
  <strong>Destino:</strong>
  <%= @trecho.destino %>
</p>

<p>
  <strong>Data ida:</strong>
  <%= @trecho.data_ida %>
</p>

<p>
  <strong>Horario ida:</strong>
  <%= @trecho.horario_ida %>
</p>

<p>
  <strong>Data volta:</strong>
  <%= @trecho.data_volta %>
</p>

<p>
  <strong>Horario volta:</strong>
  <%= @trecho.horario_volta %>
</p>

<%= link_to 'Edit', edit_trecho_path(@trecho) %> |
<%= link_to 'Back', trechos_path %>